# -*- coding: utf-8 -*-
"""workcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRgRLw6lx296_zx5nEur8ViMp1kT9gzt
"""

#exercice 1
# author : Da Fonte
# sate : ongoing

#exercice 2
# author : TD
# sate : ongoing